#!/bin/bash

sshfiles() {
  rm -rf ~/.ssh/known_hosts
  rm -rf ~/.ssh/authorized_keys
  echo "" > ~/.ssh/known_hosts
}

creategitconfig() {
  rm -rf ~/dotfiles/src/.gitconfig
  rm -rf ~/.gitconfig
  cp src/.gitconfig_default src/.gitconfig
  read -e -p "Please enter your desired git name: " GITNAME
  read -e -p "Please enter your git email: " GITEMAIL
  while read a ; do echo ${a//:name/$GITNAME} ; done < src/.gitconfig > src/.gitconfig.t ; mv src/.gitconfig{.t,}
  while read a ; do echo ${a//:email/$GITEMAIL} ; done < src/.gitconfig > src/.gitconfig.t ; mv src/.gitconfig{.t,}
  ln -sf ~/dotfiles/src/.gitconfig ~/.gitconfig;
  echo -e "${GREEN}.gitconfig link done${NC}"
}

sublimeConfig() {
  if [ ! -d ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User ]; then
    mkdir -p ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User
  fi
  
  ln -sf ~/dotfiles/sublime/Preferences.sublime-settings ~/Library/Application\ Support/Sublime\ Text\ 3/Packages/User/Preferences.sublime-settings
  echo -e "${GREEN}.Sublime text config link done${NC}"
}
